###### Hospital Patient Flow & Medical Services Analytics - Analytical SQL Queries ######

# A. Basic Aggregation
# 1. Calculate the number of admissions per department per month.
SELECT 	COUNT(*) AS NO_OF_ADMISSIONS,DEPARTMENT,
		YEAR(ADMISSION_DATE) AS YEAR_OF_ADMISSION,
		MONTHNAME(ADMISSION_DATE) AS MONTH_OF_ADMISSION,
        	MONTH(ADMISSION_DATE) AS MONTH_NUMBER
FROM PATIENT_ADMISSIONS 
GROUP BY DEPARTMENT,YEAR_OF_ADMISSION,MONTH(ADMISSION_DATE),MONTH_OF_ADMISSION 
ORDER BY DEPARTMENT,YEAR_OF_ADMISSION,MONTH(ADMISSION_DATE),MONTH_OF_ADMISSION;

#Cumulative count of admissions over all the years per department per month
SELECT 	COUNT(*) AS NO_OF_ADMISSIONS,DEPARTMENT,
		MONTH(ADMISSION_DATE) AS MONTH_OF_ADMISSION 
FROM PATIENT_ADMISSIONS 
GROUP BY DEPARTMENT, MONTH_OF_ADMISSION 
ORDER BY DEPARTMENT, MONTH_OF_ADMISSION;

# 2. Find the average treatment cost per department.
SELECT 	P.DEPARTMENT,
		ROUND(AVG(T.COST),2) AS AVERAGE_TREATMENT_COST 
FROM TREATMENT_RECORDS T 
JOIN PATIENT_ADMISSIONS P ON T.PATIENT_ID=P.PATIENT_ID 
GROUP BY P.DEPARTMENT
ORDER BY P.DEPARTMENT;

#B. Join Operations

#1. Join admissions with doctors to identify top-performing doctors by department.
#Shows all top-performing doctors with a 100% success rate
WITH DOCTOR_PERFORMANCE AS(
SELECT  T.DOCTOR_ID,
		D.SPECIALIZATION,
		SUM(T.SUCCESS) AS NO_OF_SUCCESSFUL_TREATMENTS,
		COUNT(T.PATIENT_ID) AS TOTAL_PATIENTS,
        ROUND((SUM(T.SUCCESS)/COUNT(T.PATIENT_ID))*100,2) AS SUCCESS_RATE,
        DENSE_RANK() OVER(PARTITION BY D.SPECIALIZATION ORDER BY (SUM(T.SUCCESS)/COUNT(T.PATIENT_ID))*100 DESC) AS PERFORMANCE_RANK
FROM DOCTOR_PROFILES D 
JOIN TREATMENT_RECORDS T ON D.DOCTOR_ID=T.DOCTOR_ID 
GROUP BY T.DOCTOR_ID, D.SPECIALIZATION
ORDER BY D.SPECIALIZATION, SUCCESS_RATE DESC)
SELECT * FROM DOCTOR_PERFORMANCE WHERE PERFORMANCE_RANK=1;

#To get the top-performing doctor with the highest successful treatments in each department
WITH DOCTOR_PERFORMANCE AS(
SELECT  T.DOCTOR_ID,
		D.SPECIALIZATION,
		SUM(T.SUCCESS) AS NO_OF_SUCCESSFUL_TREATMENTS,
		COUNT(T.PATIENT_ID) AS TOTAL_PATIENTS,
        	ROUND((SUM(T.SUCCESS)/COUNT(T.PATIENT_ID))*100,2) AS SUCCESS_RATE,
        	DENSE_RANK() OVER(PARTITION BY D.SPECIALIZATION ORDER BY (SUM(T.SUCCESS)/COUNT(T.PATIENT_ID))*100 DESC) AS PERFORMANCE_RANK
FROM DOCTOR_PROFILES D 
JOIN TREATMENT_RECORDS T ON D.DOCTOR_ID=T.DOCTOR_ID 
GROUP BY T.DOCTOR_ID,D.SPECIALIZATION
ORDER BY D.SPECIALIZATION,SUCCESS_RATE DESC),
MAX_SUCCESSFUL_TREATMENTS_PER_DEPARTMNT AS(
SELECT SPECIALIZATION, MAX(NO_OF_SUCCESSFUL_TREATMENTS) AS MAX_SUCCESS FROM DOCTOR_PERFORMANCE WHERE PERFORMANCE_RANK=1 GROUP BY SPECIALIZATION
)
SELECT DP.* FROM DOCTOR_PERFORMANCE DP 
JOIN MAX_SUCCESSFUL_TREATMENTS_PER_DEPARTMNT MaxPerDept ON DP.SPECIALIZATION = MaxPerDept.SPECIALIZATION
   AND DP.NO_OF_SUCCESSFUL_TREATMENTS = MaxPerDept.MAX_SUCCESS
WHERE DP.PERFORMANCE_RANK=1
ORDER BY DP.SPECIALIZATION;

#2. Join treatments with patient data to evaluate recovery rate by age group.
WITH AGE_GROUP_CALC AS
(SELECT *,CASE
		WHEN AGE BETWEEN 0 AND 17 THEN '0-17'
        	WHEN AGE BETWEEN 18 AND 44 THEN '18-44'
        	WHEN AGE BETWEEN 45 AND 64 THEN '45-64'
        	ELSE '65+'
    END AS AGE_GROUP_HEALTHCARE
FROM PATIENT_ADMISSIONS)
SELECT 	P.AGE_GROUP_HEALTHCARE AS AGE_GROUP,
		SUM(T.SUCCESS) AS NO_OF_SUCCESSFUL_TREATMENTS,
		COUNT(T.PATIENT_ID) AS TOTAL_PATIENTS,
        (SUM(T.SUCCESS)/COUNT(T.PATIENT_ID))*100 AS RECOVERY_RATE
FROM TREATMENT_RECORDS T JOIN AGE_GROUP_CALC P ON T.PATIENT_ID=P.PATIENT_ID
GROUP BY P.AGE_GROUP_HEALTHCARE ORDER BY P.AGE_GROUP_HEALTHCARE;

# C. Window Functions
#1. Calculate the moving average of daily admissions (7-day MA).
WITH DAILY_ADMISSIONS AS(
		SELECT ADMISSION_DATE, COUNT(PATIENT_ID) AS TOTAL_ADMISSIONS FROM PATIENT_ADMISSIONS GROUP BY ADMISSION_DATE ORDER BY ADMISSION_DATE
)
SELECT  *, CASE WHEN ROW_NUMBER() OVER (ORDER BY ADMISSION_DATE) >=7 THEN
ROUND(AVG(TOTAL_ADMISSIONS) OVER (ORDER BY ADMISSION_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW),2) 
                	ELSE TOTAL_ADMISSIONS
		END AS MOVING_AVG_FOR_7DAY 
FROM DAILY_ADMISSIONS;

#2. Rank doctors by number of successful treatments per month.
WITH DOCTOR_MONTHLY_SUCCESS_COUNT AS(
SELECT 	DOCTOR_ID,
		COUNT(SUCCESS) AS SUCCESS_COUNT,
        MONTH(TREATMENT_DATE) AS TREATMENT_MONTH 
FROM TREATMENT_RECORDS T 
WHERE T.SUCCESS=1 
GROUP BY DOCTOR_ID,MONTH(TREATMENT_DATE)
)
SELECT *,DENSE_RANK() OVER(PARTITION BY TREATMENT_MONTH ORDER BY SUCCESS_COUNT DESC) AS RANK_BY_MONTH 
FROM DOCTOR_MONTHLY_SUCCESS_COUNT 
ORDER BY TREATMENT_MONTH,SUCCESS_COUNT DESC;

#D. Percentiles and Median

#1. Calculate 25th, 50th, and 75th percentile of treatment costs per treatment type.
WITH RANKED AS (
    SELECT 
        TREATMENT_TYPE,
        COST,
        PERCENT_RANK() OVER (PARTITION BY TREATMENT_TYPE ORDER BY COST) AS PR
    FROM TREATMENT_RECORDS
)
SELECT 
    TREATMENT_TYPE,
    MAX(CASE WHEN PR <= 0.25 THEN COST END) AS P25,
    MAX(CASE WHEN PR <= 0.50 THEN COST END) AS P50,
    MAX(CASE WHEN PR <= 0.75 THEN COST END) AS P75
FROM RANKED
GROUP BY TREATMENT_TYPE;

#2. Find the median length of stay per department.
WITH PATIENT_STAY_LENGTH AS(
	SELECT PATIENT_ID,DEPARTMENT,DATEDIFF(DISCHARGE_DATE,ADMISSION_DATE) AS LENGTH_OF_STAY FROM PATIENT_ADMISSIONS
),
RANKED_STAY_LENGTH AS(
	SELECT DEPARTMENT,
		LENGTH_OF_STAY,
		ROW_NUMBER() OVER(PARTITION BY DEPARTMENT ORDER BY LENGTH_OF_STAY) AS RN,
        COUNT(*) OVER (PARTITION BY DEPARTMENT) AS TOTAL_COUNT
FROM PATIENT_STAY_LENGTH
)
SELECT 
    DEPARTMENT,
    CASE WHEN TOTAL_COUNT % 2 = 1 
            THEN MAX(CASE WHEN RN = (TOTAL_COUNT + 1)/2 THEN LENGTH_OF_STAY END) 
        ELSE ROUND(AVG(CASE WHEN RN IN (TOTAL_COUNT/2, TOTAL_COUNT/2 + 1) THEN LENGTH_OF_STAY END),2) 
    END AS MEDIAN_LENGTH_OF_STAY
FROM RANKED_STAY_LENGTH
GROUP BY DEPARTMENT, TOTAL_COUNT;

# E. Grouping and Case Statements

# 1. Group patients into 'High-Risk', 'Moderate-Risk', and 'Low-Risk' based on comorbidity count.
SELECT 	PATIENT_ID,
		COUNT(DISTINCT TREATMENT_TYPE) AS COMORBIDITY_COUNT,
		CASE 	WHEN COUNT(DISTINCT TREATMENT_TYPE)>=4 THEN "HIGH RISK" 
			WHEN COUNT(DISTINCT TREATMENT_TYPE)>=2 THEN "MODERATE RISK" 
			ELSE "LOW RISK" 
                	END AS RISK_CATEGORY
FROM TREATMENT_RECORDS 
GROUP BY PATIENT_ID 
ORDER BY COUNT(DISTINCT TREATMENT_TYPE) DESC;

# 2. Find admission trends by weekday and weekend.
SELECT 
	CASE WHEN DAYNAME(ADMISSION_DATE) IN ("SATURDAY","SUNDAY") THEN "WEEKEND" ELSE "WEEKDAY" END AS DAY_TYPE,
    COUNT(ADMISSION_DATE) AS TOTAL_ADMISSIONS
FROM PATIENT_ADMISSIONS
GROUP BY DAY_TYPE;

# F. Complex Joins and Subqueries

# 1. Find doctors whose patients had a recovery rate above the departmental average.
WITH DOC_PERF AS
(SELECT  T.DOCTOR_ID,
		D.SPECIALIZATION,
		SUM(T.SUCCESS) AS NO_OF_SUCCESSFUL_TREATMENTS,
		COUNT(T.PATIENT_ID) AS TOTAL_PATIENTS,
        	(SUM(T.SUCCESS)/COUNT(T.PATIENT_ID))*100 AS SUCCESS_RATE
FROM DOCTOR_PROFILES D 
JOIN TREATMENT_RECORDS T ON D.DOCTOR_ID=T.DOCTOR_ID 
GROUP BY T.DOCTOR_ID,D.SPECIALIZATION
ORDER BY D.SPECIALIZATION,SUCCESS_RATE DESC),

AVG_SUCCESS_RATE_BY_DEPT AS(
SELECT SPECIALIZATION,AVG(SUCCESS_RATE ) AS AVG_SUCCESS_RATE 
FROM DOC_PERF GROUP BY  SPECIALIZATION)

SELECT 	DP.DOCTOR_ID,
		DP.SPECIALIZATION,
        	DP.SUCCESS_RATE 
FROM DOC_PERF DP  
JOIN AVG_SUCCESS_RATE_BY_DEPT ASR ON DP.SPECIALIZATION=ASR.SPECIALIZATION 
WHERE DP.SUCCESS_RATE>ASR.AVG_SUCCESS_RATE;

# 2. Identify patients who visited more than 3 departments in a year.
SELECT 	T.PATIENT_ID, 
		YEAR(T.TREATMENT_DATE) AS TREATMENT_YEAR,
        	COUNT(DISTINCT D.SPECIALIZATION) AS DISTINCT_DEPT_VISITS
FROM TREATMENT_RECORDS T 
JOIN DOCTOR_PROFILES D ON T.DOCTOR_ID=D.DOCTOR_ID 
GROUP BY YEAR(T.TREATMENT_DATE),T.PATIENT_ID 
HAVING COUNT(DISTINCT D.SPECIALIZATION)>3 
ORDER BY COUNT(DISTINCT D.SPECIALIZATION) DESC;

# G. Date Functions and YOY

# 1. Calculate year-over-year change in total treatments administered.
WITH YEARWISE_TOTAL_TREATMENTS AS(
SELECT 	YEAR(TREATMENT_DATE) AS TREATMENT_YEAR,
		COUNT(TREATMENT_ID) AS TOTAL_TREATMENTS 
FROM TREATMENT_RECORDS 
GROUP BY TREATMENT_YEAR
)
SELECT 	*,
LAG(TOTAL_TREATMENTS) OVER (ORDER BY TREATMENT_YEAR) AS PREV_YEAR_TOTAL_TREATMENTS, 
ROUND(((TOTAL_TREATMENTS-LAG(TOTAL_TREATMENTS) OVER (ORDER BY TREATMENT_YEAR))/LAG(TOTAL_TREATMENTS) OVER (ORDER BY TREATMENT_YEAR))*100,2) AS YOY_CHANGE 
FROM YEARWISE_TOTAL_TREATMENTS;

# 2. Find the month with the highest treatment cost.
#Month with the highest treatment cost for all years combined
SELECT 
    YEAR(TREATMENT_DATE) AS Treatment_Year,
    MONTHNAME(TREATMENT_DATE) AS Month_Name,
    SUM(COST) AS Total_Treatment_Cost
FROM TREATMENT_RECORDS
GROUP BY YEAR(TREATMENT_DATE), MONTH(TREATMENT_DATE), MONTHNAME(TREATMENT_DATE)
ORDER BY Total_Treatment_Cost DESC
LIMIT 1;

# Month with the highest treatment cost per year
WITH YEARWISE_MONTHLY_TOTAL_TREATMENT_COST AS(
SELECT 	YEAR(TREATMENT_DATE) AS TREATMENT_YEAR,
		MONTHNAME(TREATMENT_DATE) AS MONTH_NAME, 
		ROUND(SUM(COST),2) AS TOTAL_TREATMENT_COST,
DENSE_RANK() OVER (PARTITION BY YEAR(TREATMENT_DATE) ORDER BY ROUND(SUM(COST),2) DESC) AS RANK_BY_TREATMENT_COST 
FROM TREATMENT_RECORDS 
GROUP BY YEAR(TREATMENT_DATE),MONTH_NAME,MONTH(TREATMENT_DATE) 
ORDER BY YEAR(TREATMENT_DATE),MONTH(TREATMENT_DATE))
SELECT * FROM YEARWISE_MONTHLY_TOTAL_TREATMENT_COST WHERE RANK_BY_TREATMENT_COST=1;

# H. Retention and Follow-up Analysis

#1. Find patients readmitted within 30 days of discharge.
WITH INTERVAL_CALC AS(
SELECT 	PATIENT_ID,
		TREATMENT_DATE,
LAG(TREATMENT_DATE) OVER (PARTITION BY PATIENT_ID ORDER BY TREATMENT_DATE) AS PREVIOUS_TREATMENT_DATE,
DATEDIFF(TREATMENT_DATE,LAG(TREATMENT_DATE) OVER (PARTITION BY PATIENT_ID ORDER BY TREATMENT_DATE)) AS INTERVAL_BETWEEN_TREATMENTS 
FROM TREATMENT_RECORDS 
ORDER BY PATIENT_ID,TREATMENT_DATE
)
SELECT  	I.PATIENT_ID, 
		P.AGE_GROUP,
        	P.GENDER, 
        	I.INTERVAL_BETWEEN_TREATMENTS 
FROM INTERVAL_CALC I 
JOIN PATIENT_ADMISSIONS P ON I.PATIENT_ID=P.PATIENT_ID 
WHERE I.INTERVAL_BETWEEN_TREATMENTS<30;

# To identify how many times the patients came back within 30 days.
WITH INTERVAL_CALC AS(
SELECT 	PATIENT_ID,
		TREATMENT_DATE,
LAG(TREATMENT_DATE) OVER (PARTITION BY PATIENT_ID ORDER BY TREATMENT_DATE) AS PREVIOUS_TREATMENT_DATE,
        	DATEDIFF(TREATMENT_DATE,LAG(TREATMENT_DATE) OVER (PARTITION BY PATIENT_ID ORDER BY TREATMENT_DATE)) AS INTERVAL_BETWEEN_TREATMENTS 
FROM TREATMENT_RECORDS 
ORDER BY PATIENT_ID,TREATMENT_DATE
)
SELECT  	I.PATIENT_ID,
		P.AGE_GROUP,
        	P.GENDER, 
        	COUNT(I.INTERVAL_BETWEEN_TREATMENTS) AS NUM_QUICK_VISITS 
FROM INTERVAL_CALC I 
JOIN PATIENT_ADMISSIONS P ON I.PATIENT_ID=P.PATIENT_ID 
WHERE I.INTERVAL_BETWEEN_TREATMENTS<30 
GROUP BY I.PATIENT_ID, P.AGE_GROUP,P.GENDER 
ORDER BY NUM_QUICK_VISITS DESC;

#2. Calculate average interval between admissions for chronic patients.
# To find overall average interval between admissions for chronic patients
WITH PATIENT_CATEGORY AS(
SELECT *,
		CASE WHEN DIAGNOSIS IN ("Hypertension", "Diabetes", "Asthma", "Cancer") THEN "CHRONIC" ELSE "NON CHRONIC" END AS PATIENT_TYPE
FROM PATIENT_ADMISSIONS
),
TREATMENT_GAPS AS (
     SELECT 
        T.PATIENT_ID,
        P.AGE_GROUP,
        P.GENDER,
        P.PATIENT_TYPE,
        T.TREATMENT_DATE,
        LAG(T.TREATMENT_DATE) OVER (PARTITION BY T.PATIENT_ID ORDER BY T.TREATMENT_DATE) AS PREV_TREATMENT_DATE
    FROM  TREATMENT_RECORDS T JOIN PATIENT_CATEGORY P  ON T.PATIENT_ID=P.PATIENT_ID WHERE P.PATIENT_TYPE="CHRONIC"
),
AVG_INTERVAL_PER_CHRONIC_PATIENT AS(
SELECT 
	PATIENT_ID,
    AGE_GROUP,
    GENDER,
    ROUND(AVG(DATEDIFF(TREATMENT_DATE, PREV_TREATMENT_DATE)),2) AS AVG_TREATMENT_INTERVAL
FROM TREATMENT_GAPS
WHERE PREV_TREATMENT_DATE IS NOT NULL
GROUP BY PATIENT_ID,AGE_GROUP,GENDER
)
SELECT ROUND(AVG(AVG_TREATMENT_INTERVAL),2) AS OVERALL_AVG_INTERVAL_FOR_CHRONIC_PATIENTS FROM AVG_INTERVAL_PER_CHRONIC_PATIENT;

# To calculate the average interval per chronic patient
WITH PATIENT_CATEGORY AS(
SELECT *,
CASE WHEN DIAGNOSIS IN ("Hypertension", "Diabetes", "Asthma", "Cancer") THEN "CHRONIC" ELSE "NON CHRONIC" END AS PATIENT_TYPE
FROM PATIENT_ADMISSIONS
),
TREATMENT_GAPS AS (
    SELECT 
        T.PATIENT_ID,
        P.AGE_GROUP,
        P.GENDER,
        P.PATIENT_TYPE,
        T.TREATMENT_DATE,
 LAG(T.TREATMENT_DATE) OVER (PARTITION BY T.PATIENT_ID ORDER BY T.TREATMENT_DATE) AS PREV_TREATMENT_DATE
FROM  TREATMENT_RECORDS T 
JOIN PATIENT_CATEGORY P  ON T.PATIENT_ID=P.PATIENT_ID 
WHERE P.PATIENT_TYPE="CHRONIC"
)
SELECT 
	PATIENT_ID,
    	AGE_GROUP,
   	GENDER,
ROUND(AVG(DATEDIFF(TREATMENT_DATE, PREV_TREATMENT_DATE)),2) AS AVG_TREATMENT_INTERVAL
FROM TREATMENT_GAPS
WHERE PREV_TREATMENT_DATE IS NOT NULL
GROUP BY PATIENT_ID,AGE_GROUP,GENDER;

